function G_vec = calc_G(in1,g,a1,a2,a3,l1,l2,l3,ml1,ml2,ml3,mm1,mm2,mm3)
%calc_G
%    G_vec = calc_G(IN1,G,A1,A2,A3,L1,L2,L3,ML1,ML2,ML3,MM1,MM2,MM3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    04-Mar-2026 19:56:54

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = q1+q2;
t4 = a1.*t2;
t5 = cos(t3);
t6 = q3+t3;
t7 = cos(t6);
t8 = a2.*t5;
t9 = l3.*t7;
G_vec = [g.*ml2.*(t4+l2.*t5)+g.*mm3.*(t4+t8)+g.*mm2.*t4+g.*ml3.*(t4+t8+t9)+g.*l1.*ml1.*t2;g.*ml3.*(t8+t9)+g.*mm3.*t8+g.*l2.*ml2.*t5;g.*ml3.*t9];
end
