function B = calc_B(in1,a1,a2,a3,l1,l2,l3,ml1,ml2,ml3,mm1,mm2,mm3,Il1,Il2,Il3,Im1,Im2,Im3,kr1,kr2,kr3)
%calc_B
%    B = calc_B(IN1,A1,A2,A3,L1,L2,L3,ML1,ML2,ML3,MM1,MM2,MM3,Il1,Il2,Il3,Im1,Im2,Im3,KR1,KR2,KR3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    04-Mar-2026 19:56:53

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = Im2.*kr2;
t5 = Im3.*kr3;
t6 = q2+q3;
t7 = a1.^2;
t8 = a2.^2;
t9 = l2.^2;
t10 = l3.^2;
t11 = cos(t6);
t12 = ml3.*t8;
t13 = mm3.*t8;
t14 = ml2.*t9;
t15 = ml3.*t10;
t16 = a1.*a2.*ml3.*t2;
t17 = a1.*a2.*mm3.*t2;
t18 = a1.*l2.*ml2.*t2;
t19 = a2.*l3.*ml3.*t3;
t20 = t19.*2.0;
t21 = a1.*l3.*ml3.*t11;
t22 = Il3+t5+t15+t19;
t23 = t21+t22;
t24 = Il2+Il3+Im3+t4+t12+t13+t14+t15+t16+t17+t18+t20+t21;
B = reshape([Il1+Il2+Il3+Im2+Im3+t12+t13+t14+t15+t16.*2.0+t17.*2.0+t18.*2.0+t20+t21.*2.0+ml2.*t7+ml3.*t7+mm2.*t7+mm3.*t7+Im1.*kr1.^2+l1.^2.*ml1,t24,t23,t24,Il2+Il3+Im3+t12+t13+t14+t15+t20+kr2.*t4,t22,t23,t22,Il3+t15+kr3.*t5],[3,3]);
end
