function C = calc_C(in1,in2,a1,a2,a3,l1,l2,l3,ml1,ml2,ml3,mm1,mm2,mm3,Il1,Il2,Il3,Im1,Im2,Im3,kr1,kr2,kr3)
%calc_C
%    C = calc_C(IN1,IN2,A1,A2,A3,L1,L2,L3,ML1,ML2,ML3,MM1,MM2,MM3,Il1,Il2,Il3,Im1,Im2,Im3,KR1,KR2,KR3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    04-Mar-2026 19:56:53

dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q2);
t3 = sin(q3);
t4 = q2+q3;
t5 = dq1+dq2+dq3;
t6 = a2.*t3;
t7 = sin(t4);
t8 = a2.*ml3.*t2;
t9 = a2.*mm3.*t2;
t10 = l2.*ml2.*t2;
t11 = a1.*t7;
t12 = dq3.*l3.*ml3.*t6;
t13 = l3.*ml3.*t7;
t14 = l3.*ml3.*t11;
t15 = -t12;
t16 = t6+t11;
t19 = t8+t9+t10+t13;
t17 = dq3.*l3.*ml3.*t16;
t20 = a1.*dq2.*t19;
t18 = -t17;
t21 = -t20;
C = reshape([t18+t21,t15+dq1.*(t14+a1.*t8+a1.*t9+a1.*t10),dq1.*(t14+l3.*ml3.*t6)+dq2.*l3.*ml3.*t6,t18+t21-a1.*dq1.*t19,t15,l3.*ml3.*t6.*(dq1+dq2),-l3.*ml3.*t5.*t16,-l3.*ml3.*t5.*t6,0.0],[3,3]);
end
